name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z.
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: bug-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should do Z.
    validations:
      required: true
  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.